FROM node:18-alpine

WORKDIR /app

# Installiere Dependencies (Force Rebuild - TS Downgrade)
COPY package*.json ./
RUN npm install

# Kopiere Source Code
COPY . .

# Exponiere Port
EXPOSE 3000

# Starte Development Server
CMD ["npm", "start"]